routes/web.php
<?php

use App\Http\Controllers\Admin\AdminPayrollController;
use App\Http\Controllers\Admin\LeagueController;
use App\Http\Controllers\Admin\MatchTeamController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\TeamController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\RegisterOfferController;
use App\Http\Controllers\Admin\ContestController;
use App\Http\Controllers\Admin\ContestRankController;
use App\Http\Controllers\Admin\ContestTeamController;
use App\Http\Controllers\Admin\CouponController;
use App\Http\Controllers\Admin\PackageController;
use App\Http\Controllers\Admin\PaymentController;
use App\Http\Controllers\Admin\PlayerController;
use App\Http\Controllers\Admin\PromocodeController;
use App\Http\Controllers\Admin\PushNotificationController;
use App\Http\Controllers\Admin\WithdrawController;
use App\Http\Controllers\Website\HomeController;
use App\Models\MatchTeam;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

Route::get('command-route', function () {
    Artisan::call('cache:clear');
    Artisan::call('migrate:fresh --seed');
});

Route::middleware('web')->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('home');
});

Route::prefix('dashboard')->middleware(['auth', 'verified'])->group(function () {
    Route::view('/', 'dashboard.dashboard')->name('dashboard');
    //Profile Setting
    Route::resource('user', UserController::class);
    Route::get('edit-profile',  [UserController::class, 'editProfile'])->name('edit.profile');
    Route::put('edit-update-profile', [UserController::class, 'updateProfile'])->name('edit.profile.update');
    Route::get('change_password', [UserController::class, 'change_password'])->name('change_password');

    Route::prefix('settings')->group(function () {
        Route::get('/company_settings', [SettingController::class, 'editCompanySetting'])->name('company.edit');
        Route::post('/company_setting', [SettingController::class, 'updateCompanySetting'])->name('company.update');
    });
    // Role Permission
    Route::resource('developer/permission', PermissionController::class)->only('index', 'store');
    Route::get('role/assign', [RoleController::class, 'roleAssign'])->name('role.assign');
    Route::post('role/assign', [RoleController::class, 'storeAssign'])->name('store.assign');
    Route::resource('role', RoleController::class);
    Route::resource('slider', SliderController::class);
    Route::resource('team', TeamController::class);
    Route::resource('league', LeagueController::class);
    Route::resource('match_team', MatchTeamController::class);
    Route::resource('contest', ContestController::class);
    Route::resource('register-offer', RegisterOfferController::class);
    Route::resource('package', PackageController::class);
    Route::resource('payment', PaymentController::class);
    Route::resource('player', PlayerController::class);
    Route::resource('withdraw', WithdrawController::class);
    Route::resource('admin_payroll', AdminPayrollController::class);
    // Route::resource('', PromocodeController::class);
    Route::resource('promocode', PromocodeController::class);


    Route::prefix('payment')->group(function () {
        Route::get('/cancel/{payment}', [PaymentController::class, 'cancel'])->name('payment.cancel');
    });
    Route::get('cancel/payment', [PaymentController::class, 'cancelHistory'])->name('payment.cancel.list');
    Route::get('approve/payment', [PaymentController::class, 'approve'])->name('payment.approve');

    Route::get('contest-rank/{id}', [ContestRankController::class, 'index'])->name('contest.rank.list'); //parameter id is contest id
    Route::post('contest-rank/store/{id}', [ContestRankController::class, 'store'])->name('contest.rank.store'); //parameter id is contest id
    Route::put('contest-rank/update/{contest_rank}', [ContestRankController::class, 'update'])->name('contest.rank.update'); //parameter id is contest id
    Route::delete('rankcontest/delete/{contest_rank}', [ContestRankController::class, 'destroy'])->name('contest.rank.delete'); //parameter id is contest id

    Route::get('player/create/{id}/{position}', [PlayerController::class, 'create'])->name('player.team.create');
    Route::post('player/team/store/{id}', [PlayerController::class, 'store'])->name('player.team.store');

    Route::get('match/live', [MatchTeamController::class, 'live'])->name('match.live');
    Route::get('match/completed', [MatchTeamController::class, 'completed'])->name('match.completed');
    Route::get('match/history', [MatchTeamController::class, 'history'])->name('match.history');
    Route::get('match/announce/player/list/{match_team}', [MatchTeamController::class, 'announcePlayers'])->name('announce.players');
    Route::get('live/score/{match_team}', [MatchTeamController::class, 'livescore'])->name('live.score');
    Route::put('live/score/{match_team}', [MatchTeamController::class, 'livescoreStore'])->name('live.score.match_team.update');

    Route::get('contest/team/complete/{id}', [ContestTeamController::class, 'complete'])->name('contest.team.complete');
    Route::get('approved/withdraw', [WithdrawController::class, 'approve'])->name('withdraw.approve');
    Route::put('cancel/withdraw/{withdraw}', [WithdrawController::class, 'cancel'])->name('cancel.withdraw');
    Route::get('contest-history', [ContestController::class, 'history'])->name('contest.history');
    Route::get('running/contest', [ContestController::class, 'running'])->name('contest.running');
    Route::get('contest/users/{id}', [ContestTeamController::class, 'users'])->name('contest.users');
    Route::post('contest/players/update', [PlayerController::class, 'updateplayers'])->name('points.update');

    Route::get('/send-notification/index', [PushNotificationController::class, 'index'])->name('notification');
    Route::get('/send-notification/create', [PushNotificationController::class, 'create'])->name('notification.create');
    Route::delete('/send-notification/delete/{notification}', [PushNotificationController::class, 'destroy'])->name('notification.destroy');


    Route::post('/send-notification', [PushNotificationController::class, 'sendNotification'])->name('send.notification');
    //coupons
});

app/Models/ContestRank.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ContestRank extends Model
{
    use HasFactory, SoftDeletes;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['contest_id', 'ranks', 'amount_type', 'amount'];
}

app/Http/Controllers/Admin/ContestRankController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\ContestRank;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Contest;

class ContestRankController extends Controller
{
    public function index($contest_id)
    {

        $ranks = ContestRank::where('contest_id', $contest_id)->get();
        return view('dashboard.contest-rank.index', compact('ranks', 'contest_id'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($contest_id)
    {
        return view('dashboard.contest.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $contest_id)
    {
        $rank = ContestRank::where('contest_id', $contest_id)->get()->last();
        $input['amount'] = $request->input('amount');
        $rank == null ? $input['ranks'] = 1 : $input['ranks'] = increment($rank->ranks);
        $input['contest_id'] = $contest_id;
        $input['amount_type'] = 'money';
        ContestRank::create($input);
        return back()->with('success', 'Contest Rank Create Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\ContestRank  $contestRank
     * @return \Illuminate\Http\Response
     */
    public function show(ContestRank $contestRank)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\ContestRank  $contestRank
     * @return \Illuminate\Http\Response
     */
    public function edit(ContestRank $contestRank)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\ContestRank  $contestRank
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ContestRank $contestRank)
    {
        $contestRank->amount = $request->input('amount');
        $contestRank->save();
        return back()->with('success', 'Rank Update Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\ContestRank  $contestRank
     * @return \Illuminate\Http\Response
     */
    public function destroy(ContestRank $contestRank)
    {
        $contestRank->delete();
        return back()->with('success', 'Rank Delete successfully');
    }
}

app/Http/Controllers/Api/ContestRankController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\ContestRank;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ContestRankController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\ContestRank  $contestRank
     * @return \Illuminate\Http\Response
     */
    public function show(ContestRank $contestRank)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\ContestRank  $contestRank
     * @return \Illuminate\Http\Response
     */
    public function edit(ContestRank $contestRank)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\ContestRank  $contestRank
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ContestRank $contestRank)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\ContestRank  $contestRank
     * @return \Illuminate\Http\Response
     */
    public function destroy(ContestRank $contestRank)
    {
        //
    }
}

resources/views/dashboard/contest-rank/create.blade.php
@extends('layouts.dashboard')
@section('content')
    <div class="card card-custom card-sticky" id="kt_page_sticky_card">
        <div class="card-header">
            <div class="card-title">
                <h3 class="card-label">
                    Create Contest
                </h3>
            </div>
            <div class="card-toolbar">
                <div class="btn-group">
                    <button type="submit" form="kt_form" class="btn btn-primary font-weight-bolder submit">
                        <i class="ki ki-check icon-sm"></i>
                        Save Form
                    </button>
                </div>
            </div>
        </div>
        <!--begin::Portlet-->
        <div class="card-body">
            <form class="form" id="kt_form" enctype="multipart/form-data" method="POST"
                action="{{ route('contest.store') }}">
                @csrf
                <div class="row justify-content-center">
                    <div class="col-lg-8">
                        <div class="form-group">
                            <label for="name">{{ __('Name') }} <span class="text-danger">*</span></label>
                            <input name="name" id="name" value="{{ old('name') }}"
                                class="form-control form-control-solid @error('name') is-invalid @enderror" type="text"
                                placeholder="Team Name">
                            @error('name')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="shortname">{{ __('Short Name') }} <span class="text-danger">*</span></label>
                            <input name="shortname" id="shortname" value="{{ old('shortname') }}"
                                class="form-control form-control-solid @error('shortname') is-invalid @enderror" type="text"
                                placeholder="Team Name">
                            @error('shortname')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="match_id">{{ __('Choose Match') }} <span class="text-danger">*</span></label>
                            <select class="form-control " id="match_id" name="match_id">
                                <option value="">Select Match</option>
                                @foreach ($matches as $match)
                                    <option value="{{ $match->id }}">{{ $match->teamoneOne->name }} <b>vs</b>
                                        {{ $match->teamtwoOne->name }}</option>
                                @endforeach
                            </select>
                            @error('shortname')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="entry_fee">{{ __('Entry Fee') }} <span class="text-danger">*</span></label>
                            <input name="entry_fee" id="entry_fee" value="{{ old('entry_fee') }}"
                                class="form-control form-control-solid @error('entry_fee') is-invalid @enderror" type="number"
                                placeholder="Entry Fee">
                            @error('entry_fee')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="entry_fee_type">{{ __('Entry Fee Type') }} <span
                                    class="text-danger">*</span></label>
                            <select class="form-control " id="entry_fee_type" name="entry_fee_type">
                                <option value="">Choose Entry Fee Type</option>
                                <option value="coin">Coin</option>
                                <option value="money">Money</option>
                            </select>
                            @error('entry_fee_type')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="balance">{{ __('Balance') }} <span class="text-danger">*</span></label>
                            <input name="balance" id="balance" value="{{ old('balance') }}"
                                class="form-control form-control-solid @error('balance') is-invalid @enderror" type="number"
                                placeholder="Entry Fee">
                            @error('balance')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="balance_type">{{ __('Balance Type') }} <span
                                    class="text-danger">*</span></label>
                            <select class="form-control " id="balance_type" name="balance_type">
                                <option value="">Choose Entry Fee Type</option>
                                <option value="coin">Coin</option>
                                <option value="money">Money</option>
                            </select>
                            @error('balance_type')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="form-group row">
                            <label class="col-md-3 col-form-label" for="status">Status</label>
                            <div class="col-md-9">
                                <input type="hidden" checked value="0" name="status" />
                                <span class="switch switch-icon">
                                    <label>
                                        <input type="checkbox" {{ old('status', 1) ? 'checked' : null }} value="1"
                                            name="status" />
                                        <span></span>
                                    </label>
                                </span>

                                @error('status')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@push('script')
    <script src="{{ asset('assets/dashboard/js/pages/crud/file-upload/image-input.js') }}"></script>
    <script>
        let avatar5 = new KTImageInput('logo');
        let avatar6 = new KTImageInput('footerLogo');
    </script>
@endpush

resources/views/dashboard/contest-rank/edit.blade.php
@extends('layouts.dashboard')
@section('content')
    <div class="card card-custom card-sticky" id="kt_page_sticky_card">
        <div class="card-header">
            <div class="card-title">
                <h3 class="card-label">
                    Update Contest
                </h3>
            </div>
            <div class="card-toolbar">
                <div class="btn-group">
                    <button type="submit" form="kt_form" class="btn btn-primary font-weight-bolder submit">
                        <i class="ki ki-check icon-sm"></i>
                        Update Form
                    </button>
                </div>
            </div>
        </div>
        <!--begin::Portlet-->
        <div class="card-body">
            <form class="form" id="kt_form" enctype="multipart/form-data" method="POST"
                action="{{ route('contest.update', $contest->id) }}">
                @csrf
                @method('PUT')
                <div class="row justify-content-center">
                    <div class="col-lg-8">
                        <div class="form-group">
                            <label for="name">{{ __('Name') }} <span class="text-danger">*</span></label>
                            <input name="name" id="name" value="{{ $contest->name }}"
                                class="form-control form-control-solid @error('name') is-invalid @enderror" type="text"
                                placeholder="Team Name">
                            @error('name')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="shortname">{{ __('Short Name') }} <span class="text-danger">*</span></label>
                            <input name="shortname" id="shortname" value="{{ $contest->shortname }}"
                                class="form-control form-control-solid @error('shortname') is-invalid @enderror" type="text"
                                placeholder="Team Name">
                            @error('shortname')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="match_id">{{ __('Choose Match') }} <span class="text-danger">*</span></label>
                            <select class="form-control " id="match_id" name="match_id">
                                <option value="">Select Match</option>
                                @foreach ($matches as $match)
                                    <option value="{{ $match->id }}" @if($match->id == $contest->match_id) Selected @endif>{{ $match->teamoneOne->name }} <b>vs</b>
                                        {{ $match->teamtwoOne->name }}</option>
                                @endforeach
                            </select>
                            @error('shortname')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="entry_fee">{{ __('Entry Fee') }} <span class="text-danger">*</span></label>
                            <input name="entry_fee" id="entry_fee" value="{{ $contest->entry_fee }}"
                                class="form-control form-control-solid @error('entry_fee') is-invalid @enderror" type="number"
                                placeholder="Entry Fee">
                            @error('entry_fee')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="entry_fee_type">{{ __('Entry Fee Type') }} <span
                                    class="text-danger">*</span></label>
                            <select class="form-control " id="entry_fee_type" name="entry_fee_type">
                                <option value="">Choose Entry Fee Type</option>
                                <option value="coin" @if($contest->entry_fee_type == "coin") Selected @endif>Coin</option>
                                <option value="money" @if($contest->entry_fee_type == "money") Selected @endif>Money</option>
                            </select>
                            @error('entry_fee_type')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="balance">{{ __('Balance') }} <span class="text-danger">*</span></label>
                            <input name="balance" id="balance" value="{{ $contest->balance }}"
                                class="form-control form-control-solid @error('balance') is-invalid @enderror" type="number"
                                placeholder="Entry Fee">
                            @error('balance')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="balance_type">{{ __('Balance Type') }} <span
                                    class="text-danger">*</span></label>
                            <select class="form-control " id="balance_type" name="balance_type">
                                <option value="">Choose Entry Fee Type</option>
                                <option value="coin" @if($contest->balance_type == "coin") Selected @endif>Coin</option>
                                <option value="money" @if($contest->balance_type == "money") Selected @endif>Money</option>
                            </select>
                            @error('balance_type')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="form-group row">
                            <label class="col-md-3 col-form-label" for="status">Status</label>
                            <div class="col-md-9">
                                <input type="hidden" checked value="0" name="status" />
                                <span class="switch switch-icon">
                                    <label>
                                        <input type="checkbox" {{ ($contest->status == 1) ? 'checked' : null }} value="1"
                                            name="status" />
                                        <span></span>
                                    </label>
                                </span>

                                @error('status')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@push('script')
    <script src="{{ asset('assets/dashboard/js/pages/crud/file-upload/image-input.js') }}"></script>
    <script>
        let avatar5 = new KTImageInput('logo');
        let avatar6 = new KTImageInput('footerLogo');
    </script>
@endpush