routes/web.php
<?php

use App\Http\Controllers\Admin\AdminPayrollController;
use App\Http\Controllers\Admin\LeagueController;
use App\Http\Controllers\Admin\MatchTeamController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\TeamController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\RegisterOfferController;
use App\Http\Controllers\Admin\ContestController;
use App\Http\Controllers\Admin\ContestRankController;
use App\Http\Controllers\Admin\ContestTeamController;
use App\Http\Controllers\Admin\CouponController;
use App\Http\Controllers\Admin\PackageController;
use App\Http\Controllers\Admin\PaymentController;
use App\Http\Controllers\Admin\PlayerController;
use App\Http\Controllers\Admin\PromocodeController;
use App\Http\Controllers\Admin\PushNotificationController;
use App\Http\Controllers\Admin\WithdrawController;
use App\Http\Controllers\Website\HomeController;
use App\Models\MatchTeam;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

Route::get('command-route', function () {
    Artisan::call('cache:clear');
    Artisan::call('migrate:fresh --seed');
});

Route::middleware('web')->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('home');
});

Route::prefix('dashboard')->middleware(['auth', 'verified'])->group(function () {
    Route::view('/', 'dashboard.dashboard')->name('dashboard');
    //Profile Setting
    Route::resource('user', UserController::class);
    Route::get('edit-profile',  [UserController::class, 'editProfile'])->name('edit.profile');
    Route::put('edit-update-profile', [UserController::class, 'updateProfile'])->name('edit.profile.update');
    Route::get('change_password', [UserController::class, 'change_password'])->name('change_password');

    Route::prefix('settings')->group(function () {
        Route::get('/company_settings', [SettingController::class, 'editCompanySetting'])->name('company.edit');
        Route::post('/company_setting', [SettingController::class, 'updateCompanySetting'])->name('company.update');
    });
    // Role Permission
    Route::resource('developer/permission', PermissionController::class)->only('index', 'store');
    Route::get('role/assign', [RoleController::class, 'roleAssign'])->name('role.assign');
    Route::post('role/assign', [RoleController::class, 'storeAssign'])->name('store.assign');
    Route::resource('role', RoleController::class);
    Route::resource('slider', SliderController::class);
    Route::resource('team', TeamController::class);
    Route::resource('league', LeagueController::class);
    Route::resource('match_team', MatchTeamController::class);
    Route::resource('contest', ContestController::class);
    Route::resource('register-offer', RegisterOfferController::class);
    Route::resource('package', PackageController::class);
    Route::resource('payment', PaymentController::class);
    Route::resource('player', PlayerController::class);
    Route::resource('withdraw', WithdrawController::class);
    Route::resource('admin_payroll', AdminPayrollController::class);
    // Route::resource('', PromocodeController::class);
    Route::resource('promocode', PromocodeController::class);


    Route::prefix('payment')->group(function () {
        Route::get('/cancel/{payment}', [PaymentController::class, 'cancel'])->name('payment.cancel');
    });
    Route::get('cancel/payment', [PaymentController::class, 'cancelHistory'])->name('payment.cancel.list');
    Route::get('approve/payment', [PaymentController::class, 'approve'])->name('payment.approve');

    Route::get('contest-rank/{id}', [ContestRankController::class, 'index'])->name('contest.rank.list'); //parameter id is contest id
    Route::post('contest-rank/store/{id}', [ContestRankController::class, 'store'])->name('contest.rank.store'); //parameter id is contest id
    Route::put('contest-rank/update/{contest_rank}', [ContestRankController::class, 'update'])->name('contest.rank.update'); //parameter id is contest id
    Route::delete('rankcontest/delete/{contest_rank}', [ContestRankController::class, 'destroy'])->name('contest.rank.delete'); //parameter id is contest id

    Route::get('player/create/{id}/{position}', [PlayerController::class, 'create'])->name('player.team.create');
    Route::post('player/team/store/{id}', [PlayerController::class, 'store'])->name('player.team.store');

    Route::get('match/live', [MatchTeamController::class, 'live'])->name('match.live');
    Route::get('match/completed', [MatchTeamController::class, 'completed'])->name('match.completed');
    Route::get('match/history', [MatchTeamController::class, 'history'])->name('match.history');
    Route::get('match/announce/player/list/{match_team}', [MatchTeamController::class, 'announcePlayers'])->name('announce.players');
    Route::get('live/score/{match_team}', [MatchTeamController::class, 'livescore'])->name('live.score');
    Route::put('live/score/{match_team}', [MatchTeamController::class, 'livescoreStore'])->name('live.score.match_team.update');

    Route::get('contest/team/complete/{id}', [ContestTeamController::class, 'complete'])->name('contest.team.complete');
    Route::get('approved/withdraw', [WithdrawController::class, 'approve'])->name('withdraw.approve');
    Route::put('cancel/withdraw/{withdraw}', [WithdrawController::class, 'cancel'])->name('cancel.withdraw');
    Route::get('contest-history', [ContestController::class, 'history'])->name('contest.history');
    Route::get('running/contest', [ContestController::class, 'running'])->name('contest.running');
    Route::get('contest/users/{id}', [ContestTeamController::class, 'users'])->name('contest.users');
    Route::post('contest/players/update', [PlayerController::class, 'updateplayers'])->name('points.update');

    Route::get('/send-notification/index', [PushNotificationController::class, 'index'])->name('notification');
    Route::get('/send-notification/create', [PushNotificationController::class, 'create'])->name('notification.create');
    Route::delete('/send-notification/delete/{notification}', [PushNotificationController::class, 'destroy'])->name('notification.destroy');


    Route::post('/send-notification', [PushNotificationController::class, 'sendNotification'])->name('send.notification');
    //coupons
});

resources/views/dashboard/payroll/create.blade.php
@extends('layouts.dashboard')
@section('content')
    <div class="card card-custom card-sticky" id="kt_page_sticky_card">
        <div class="card-header">
            <div class="card-title">
                <h3 class="card-label">
                    Package Information
                </h3>
            </div>
            <div class="card-toolbar">
                <div class="btn-group">
                    <button type="submit" form="kt_form" class="btn btn-primary font-weight-bolder submit">
                        <i class="ki ki-check icon-sm"></i>
                        Save Form
                    </button>
                </div>
            </div>
        </div>
        <!--begin::Portlet-->
        <div class="card-body">
            <form class="form" id="kt_form" method="POST" action="{{ route('admin_payroll.store') }}">
                @csrf
                <div class="row justify-content-center">
                    <div class="col-lg-10">
                        <div class="form-group">
                          <label for="mobile">Mobile</label>
                          <input type="text"
                            class="form-control" name="mobile" id="mobile" aria-describedby="mobileId" placeholder="Enter Mobile/Accountg Number">
                          <small id="nameId" class="form-text text-muted">Phone/Account Number</small>
                        </div>
                        @error('mobile')
                            <div class="text-danger">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="row justify-content-around">
                    <div class="col-lg-4">
                      {{-- start  --}}
                        <div class="form-group">
                          <label for="methodId">Method</label>
                          <select class="form-control" name="method" id="methodId">
                              <option value="bkash">Bkash -BRAC Bank Limited</option>
                              <option value="nagad">Nagad -Bangladesh Post Office</option>
                          </select>
                        </div>
                        @error('method')
                            <div class="text-danger">{{ $message }}</div>
                        @enderror
                    </div>
                  <div class="col-lg-11  offset-lg-1 d-flex">
                    <label class="col-form-label mr-2" for="status">Status</label>
                      <input type="hidden" checked value="0" name="status" />
                      <span class="switch switch-icon">
                          <label>
                              <input type="checkbox" {{ old('status', 1) ? 'checked' : null }} value="1"
                                  name="status" />
                              <span></span>
                          </label>
                      </span>
                      @error('status')
                          <div class="text-danger">{{ $message }}</div>
                      @enderror
                  </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/dashboard/payroll/edit.blade.php
@extends('layouts.dashboard')
@section('content')
    <div class="card card-custom card-sticky" id="kt_page_sticky_card">
        <div class="card-header">
            <div class="card-title">
                <h3 class="card-label">
                    Package Information
                </h3>
            </div>
            <div class="card-toolbar">
                <div class="btn-group">
                    <button type="submit" form="kt_form" class="btn btn-primary font-weight-bolder submit">
                        <i class="ki ki-check icon-sm"></i>
                        Save Form
                    </button>
                </div>
            </div>
        </div>
        <!--begin::Portlet-->
        <div class="card-body">
            <form class="form" id="kt_form" method="POST" action="{{ route('admin_payroll.update', $adminPayroll->id) }}">
                @csrf
                @method('PUT')
                <div class="row justify-content-center">
                    <div class="col-lg-10">
                        <div class="form-group">
                          <label for="mobile">Mobile</label>
                          <input type="text"
                            class="form-control" name="mobile" value="{{ $adminPayroll->mobile }}" id="mobile" aria-describedby="mobileId" placeholder="Enter Mobile/Accountg Number">
                          <small id="nameId" class="form-text text-muted">Phone/Account Number</small>
                        </div>
                        @error('mobile')
                            <div class="text-danger">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="row justify-content-around">
                    <div class="col-lg-4">
                      {{-- start  --}}
                        <div class="form-group">
                          <label for="methodId">Method</label>
                          <select class="form-control" name="method" id="methodId">
                              <option value="bkash" @if ($adminPayroll->method == "bkash") selected @endif>Bkash -BRAC Bank Limited</option>
                              <option value="nagad" @if ($adminPayroll->method == "nagad") selected @endif>Nagad -Bangladesh Post Office</option>
                          </select>
                        </div>
                        @error('method')
                            <div class="text-danger">{{ $message }}</div>
                        @enderror
                    </div>
                  <div class="col-lg-11  offset-lg-1 d-flex">
                    <label class="col-form-label mr-2" for="status">Status</label>
                      <input type="hidden" checked value="0" name="status" />
                      <span class="switch switch-icon">
                          <label>
                              <input type="checkbox" @if($adminPayroll->status == 1) checked @endif value="1"
                                  name="status" />
                              <span></span>
                          </label>
                      </span>
                      @error('status')
                          <div class="text-danger">{{ $message }}</div>
                      @enderror
                  </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/dashboard/payroll/index.blade.php
@extends('layouts.dashboard')
@section('content')
    <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
        <div class="kt-portlet kt-portlet--mobile">
            <div class="card card-custom mt-5">
                <div class="card-header flex-wrap border-0 pt-6 pb-0">
                    <div class="card-title">
                        <h3 class="card-label">Admin Payroll List</h3>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-separate table-head-custom table-checkable" id="kt_datatable">
                        <thead>
                            <tr>
                                <th>SL</th>
                                <th>Mobile</th>
                                <th>Method</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($payrolls as $key => $payroll)
                                <tr>
                                    <td>{{ $key++ }}</td>
                                    <td>{{ $payroll->mobile }}</td>
                                    <td>{{ $payroll->method }}</td>
                                    <td>{{ $payroll->status == 1 ? "Active" : "Close" }}</td>
                                    <td nowrap="nowrap">
                                        <a href="{{ route('admin_payroll.edit', $payroll->id) }}"
                                            class="btn btn-icon btn-light btn-hover-primary btn-sm mx-3">
                                            <span class="svg-icon svg-icon-md svg-icon-primary">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px"
                                                    viewBox="0 0 24 24" version="1.1">
                                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                        <rect x="0" y="0" width="24" height="24"></rect>
                                                        <path
                                                            d="M12.2674799,18.2323597 L12.0084872,5.45852451 C12.0004303,5.06114792 12.1504154,4.6768183 12.4255037,4.38993949 L15.0030167,1.70195304 L17.5910752,4.40093695 C17.8599071,4.6812911 18.0095067,5.05499603 18.0083938,5.44341307 L17.9718262,18.2062508 C17.9694575,19.0329966 17.2985816,19.701953 16.4718324,19.701953 L13.7671717,19.701953 C12.9505952,19.701953 12.2840328,19.0487684 12.2674799,18.2323597 Z"
                                                            fill="#000000" fill-rule="nonzero"
                                                            transform="translate(14.701953, 10.701953) rotate(-135.000000) translate(-14.701953, -10.701953)">
                                                        </path>
                                                        <path
                                                            d="M12.9,2 C13.4522847,2 13.9,2.44771525 13.9,3 C13.9,3.55228475 13.4522847,4 12.9,4 L6,4 C4.8954305,4 4,4.8954305 4,6 L4,18 C4,19.1045695 4.8954305,20 6,20 L18,20 C19.1045695,20 20,19.1045695 20,18 L20,13 C20,12.4477153 20.4477153,12 21,12 C21.5522847,12 22,12.4477153 22,13 L22,18 C22,20.209139 20.209139,22 18,22 L6,22 C3.790861,22 2,20.209139 2,18 L2,6 C2,3.790861 3.790861,2 6,2 L12.9,2 Z"
                                                            fill="#000000" fill-rule="nonzero" opacity="0.3"></path>
                                                    </g>
                                                </svg>
                                            </span>
                                        </a>
                                        <form method="post" action="{{ route('admin_payroll.destroy', $payroll->id) }}"
                                            class="d-inline-block">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit"
                                                onclick="return confirm('Are you sure you want to delete this Pay roll?');"
                                                class="btn btn-icon btn-light btn-hover-danger btn-sm">
                                                <span class="svg-icon svg-icon-md svg-icon-primary">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px"
                                                        viewBox="0 0 24 24" version="1.1">
                                                        <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                            <rect x="0" y="0" width="24" height="24"></rect>
                                                            <path
                                                                d="M6,8 L6,20.5 C6,21.3284271 6.67157288,22 7.5,22 L16.5,22 C17.3284271,22 18,21.3284271 18,20.5 L18,8 L6,8 Z"
                                                                fill="#000000" fill-rule="nonzero"></path>
                                                            <path
                                                                d="M14,4.5 L14,4 C14,3.44771525 13.5522847,3 13,3 L11,3 C10.4477153,3 10,3.44771525 10,4 L10,4.5 L5.5,4.5 C5.22385763,4.5 5,4.72385763 5,5 L5,5.5 C5,5.77614237 5.22385763,6 5.5,6 L18.5,6 C18.7761424,6 19,5.77614237 19,5.5 L19,5 C19,4.72385763 18.7761424,4.5 18.5,4.5 L14,4.5 Z"
                                                                fill="#000000" opacity="0.3"></path>
                                                        </g>
                                                    </svg>
                                                </span>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection