routes/web.php
<?php

use App\Http\Controllers\Admin\AdminPayrollController;
use App\Http\Controllers\Admin\LeagueController;
use App\Http\Controllers\Admin\MatchTeamController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\TeamController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\RegisterOfferController;
use App\Http\Controllers\Admin\ContestController;
use App\Http\Controllers\Admin\ContestRankController;
use App\Http\Controllers\Admin\ContestTeamController;
use App\Http\Controllers\Admin\CouponController;
use App\Http\Controllers\Admin\PackageController;
use App\Http\Controllers\Admin\PaymentController;
use App\Http\Controllers\Admin\PlayerController;
use App\Http\Controllers\Admin\PromocodeController;
use App\Http\Controllers\Admin\PushNotificationController;
use App\Http\Controllers\Admin\WithdrawController;
use App\Http\Controllers\Website\HomeController;
use App\Models\MatchTeam;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

Route::get('command-route', function () {
    Artisan::call('cache:clear');
    Artisan::call('migrate:fresh --seed');
});

Route::middleware('web')->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('home');
});

Route::prefix('dashboard')->middleware(['auth', 'verified'])->group(function () {
    Route::view('/', 'dashboard.dashboard')->name('dashboard');
    //Profile Setting
    Route::resource('user', UserController::class);
    Route::get('edit-profile',  [UserController::class, 'editProfile'])->name('edit.profile');
    Route::put('edit-update-profile', [UserController::class, 'updateProfile'])->name('edit.profile.update');
    Route::get('change_password', [UserController::class, 'change_password'])->name('change_password');

    Route::prefix('settings')->group(function () {
        Route::get('/company_settings', [SettingController::class, 'editCompanySetting'])->name('company.edit');
        Route::post('/company_setting', [SettingController::class, 'updateCompanySetting'])->name('company.update');
    });
    // Role Permission
    Route::resource('developer/permission', PermissionController::class)->only('index', 'store');
    Route::get('role/assign', [RoleController::class, 'roleAssign'])->name('role.assign');
    Route::post('role/assign', [RoleController::class, 'storeAssign'])->name('store.assign');
    Route::resource('role', RoleController::class);
    Route::resource('slider', SliderController::class);
    Route::resource('team', TeamController::class);
    Route::resource('league', LeagueController::class);
    Route::resource('match_team', MatchTeamController::class);
    Route::resource('contest', ContestController::class);
    Route::resource('register-offer', RegisterOfferController::class);
    Route::resource('package', PackageController::class);
    Route::resource('payment', PaymentController::class);
    Route::resource('player', PlayerController::class);
    Route::resource('withdraw', WithdrawController::class);
    Route::resource('admin_payroll', AdminPayrollController::class);
    // Route::resource('', PromocodeController::class);
    Route::resource('promocode', PromocodeController::class);


    Route::prefix('payment')->group(function () {
        Route::get('/cancel/{payment}', [PaymentController::class, 'cancel'])->name('payment.cancel');
    });
    Route::get('cancel/payment', [PaymentController::class, 'cancelHistory'])->name('payment.cancel.list');
    Route::get('approve/payment', [PaymentController::class, 'approve'])->name('payment.approve');

    Route::get('contest-rank/{id}', [ContestRankController::class, 'index'])->name('contest.rank.list'); //parameter id is contest id
    Route::post('contest-rank/store/{id}', [ContestRankController::class, 'store'])->name('contest.rank.store'); //parameter id is contest id
    Route::put('contest-rank/update/{contest_rank}', [ContestRankController::class, 'update'])->name('contest.rank.update'); //parameter id is contest id
    Route::delete('rankcontest/delete/{contest_rank}', [ContestRankController::class, 'destroy'])->name('contest.rank.delete'); //parameter id is contest id

    Route::get('player/create/{id}/{position}', [PlayerController::class, 'create'])->name('player.team.create');
    Route::post('player/team/store/{id}', [PlayerController::class, 'store'])->name('player.team.store');

    Route::get('match/live', [MatchTeamController::class, 'live'])->name('match.live');
    Route::get('match/completed', [MatchTeamController::class, 'completed'])->name('match.completed');
    Route::get('match/history', [MatchTeamController::class, 'history'])->name('match.history');
    Route::get('match/announce/player/list/{match_team}', [MatchTeamController::class, 'announcePlayers'])->name('announce.players');
    Route::get('live/score/{match_team}', [MatchTeamController::class, 'livescore'])->name('live.score');
    Route::put('live/score/{match_team}', [MatchTeamController::class, 'livescoreStore'])->name('live.score.match_team.update');

    Route::get('contest/team/complete/{id}', [ContestTeamController::class, 'complete'])->name('contest.team.complete');
    Route::get('approved/withdraw', [WithdrawController::class, 'approve'])->name('withdraw.approve');
    Route::put('cancel/withdraw/{withdraw}', [WithdrawController::class, 'cancel'])->name('cancel.withdraw');
    Route::get('contest-history', [ContestController::class, 'history'])->name('contest.history');
    Route::get('running/contest', [ContestController::class, 'running'])->name('contest.running');
    Route::get('contest/users/{id}', [ContestTeamController::class, 'users'])->name('contest.users');
    Route::post('contest/players/update', [PlayerController::class, 'updateplayers'])->name('points.update');

    Route::get('/send-notification/index', [PushNotificationController::class, 'index'])->name('notification');
    Route::get('/send-notification/create', [PushNotificationController::class, 'create'])->name('notification.create');
    Route::delete('/send-notification/delete/{notification}', [PushNotificationController::class, 'destroy'])->name('notification.destroy');


    Route::post('/send-notification', [PushNotificationController::class, 'sendNotification'])->name('send.notification');
    //coupons
});

app/Models/Slider.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Slider extends Model implements HasMedia
{
    use HasFactory , InteractsWithMedia;


    protected $fillable = [
        'name',
        'status',
        'image',
      ];

      public function registerMediaCollections(): void
      {
          $this->addMediaCollection('sliderImage')->singleFile();
      }


}

app/Http/Controllers/Admin/SliderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\SliderRequest;
use App\Models\Slider;
use Illuminate\Http\Request;

class SliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sliders= Slider::with('media')->get();

        // dd($sliders);


         return view('dashboard.slider.index', compact('sliders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.slider.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'             => 'required|string',
            'Slider_imgae'             => 'required|image|mimes:jpeg,png,jpg|max:1024',
            'status' => 'boolean'

        ]);
        $input = $request->all();
        $slider = Slider::create($input);
        if($request->hasFile('Slider_imgae') ){
            $slider->addMediaFromRequest('Slider_imgae')->toMediaCollection('sliderImage');
        }

        return back()->with('success', 'Slider Created.');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($user)
    {
        $sliders= Slider::with('media')->where('id', $user)->first();
         return view('dashboard.slider.edit', compact('sliders'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $user)
    {
        $request->validate([
            'name'             => 'required|string',
            'Slider_imgae'             => 'nullable|image|mimes:jpeg,png,jpg|max:1024',
            'status' => 'boolean'

        ]);
        $slider = Slider::find($user);
        $slider->update([
            'name' =>  $request->input('name'),
            'status' =>  $request->input('status'),

        ]);

        if($request->hasFile('Slider_imgae') ){
            $slider->addMediaFromRequest('Slider_imgae')->toMediaCollection('sliderImage');
        }

        return back()->with('success', 'Slider Updated.');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($user)
    {
        $slider = Slider::find($user);
        $slider->delete();

         return back()->with('success', 'Slider Deleted successfully.');
    }
}

app/Http/Controllers/Api/SliderController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\SliderCollection;
use App\Http\Resources\SliderResource;
use App\Models\Slider;
use Illuminate\Http\Request;

class SliderController extends Controller
{



    public function index(){

        $slider = SliderResource::collection(Slider::with('media')->get()) ;

        return response()->json([
            'slider' => $slider,
            'message' => 'Slider List',
        ], 201);

    }
}

resources/views/dashboard/slider/create.blade.php
@extends('layouts.dashboard')
@section('content')
    <div class="card card-custom card-sticky" id="kt_page_sticky_card">
        <div class="card-header">
            <div class="card-title">
                <h3 class="card-label">
                    Slider Information
                </h3>
            </div>
            <div class="card-toolbar">
                <div class="btn-group">
                    <button type="submit" form="kt_form" class="btn btn-primary font-weight-bolder submit">
                        <i class="ki ki-check icon-sm"></i>
                        Save Form
                    </button>
                </div>
            </div>
        </div>
        <!--begin::Portlet-->
        <div class="card-body">
            <form class="form" id="kt_form" enctype="multipart/form-data" method="POST"
                action="{{ route('slider.store') }}">
                @csrf
                <div class="row justify-content-center">
                    <div class="col-lg-8">
                        <div class="form-group">
                            <label for="name">{{ __('Name') }} <span class="text-danger">*</span></label>
                            <input name="name" id="name" value="{{ old('name') }}"
                                class="form-control form-control-solid @error('name') is-invalid @enderror" type="text"
                                placeholder="Slider Name">
                            @error('name')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="image" class="d-block">{{ __('Slider') }}</label>
                                    <div class="image-input image-input-empty image-input-outline" id="logo"
                                        style="background-image: url({{ asset('storage/') }})">
                                        <div class="image-input-wrapper"></div>
                                        <label
                                            class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow"
                                            data-action="change" data-toggle="tooltip" title=""
                                            data-original-title="Change avatar">
                                            <i class="fa fa-pen icon-sm text-muted"></i>
                                            <input type="file" name="Slider_imgae" accept=".png, .jpg, .jpeg" />
                                            <input type="hidden" name="Slider_imgae" />
                                        </label>
                                        <span
                                            class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow"
                                            data-action="cancel" data-toggle="tooltip" title="Cancel avatar">
                                            <i class="ki ki-bold-close icon-xs text-muted"></i>
                                        </span>
                                        <span
                                            class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow"
                                            data-action="remove" data-toggle="tooltip" title="Remove avatar">
                                            <i class="ki ki-bold-close icon-xs text-muted"></i>
                                        </span>
                                        @error('Slider_imgae')
                                            <div class="text-danger">{{ $message }}</div>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-3 col-form-label" for="status">Status</label>
                            <div class="col-md-9">
                                <input type="hidden" checked value="0" name="status" />
                                <span class="switch switch-icon">
                                    <label>
                                        <input type="checkbox" {{ old('status', 1) ? 'checked' : null }} value="1"
                                            name="status" />
                                        <span></span>
                                    </label>
                                </span>

                                @error('status')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@push('script')
    <script src="{{ asset('assets/dashboard/js/pages/crud/file-upload/image-input.js') }}"></script>
    <script>
        let avatar5 = new KTImageInput('logo');
        let avatar6 = new KTImageInput('footerLogo');
    </script>
@endpush

resources/views/dashboard/slider/edit.blade.php
@extends('layouts.dashboard')
@section('content')
    <div class="card card-custom card-sticky" id="kt_page_sticky_card">
        <div class="card-header">
            <div class="card-title">
                <h3 class="card-label">
                    Slider Information
                </h3>
            </div>
            <div class="card-toolbar">
                <div class="btn-group">
                    <button type="submit" form="kt_form" class="btn btn-primary font-weight-bolder submit">
                        <i class="ki ki-check icon-sm"></i>
                        Save Form
                    </button>
                </div>
            </div>
        </div>
        <!--begin::Portlet-->
        <div class="card-body">
            <form class="form" id="kt_form" enctype="multipart/form-data" method="POST"
                action="{{ route('slider.update', $sliders->id) }}">
                @csrf
                @method("put")
                <div class="row justify-content-center">
                    <div class="col-lg-8">
                        <div class="form-group">
                            <label for="name">{{ __('Name') }} <span class="text-danger">*</span></label>
                            <input name="name" id="name" value="{{ old('name') ?? $sliders->name ?? 'Slider Name'}}"
                                class="form-control form-control-solid @error('name') is-invalid @enderror" type="text"
                                placeholder="Slider Name">
                            @error('name')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="image" class="d-block">{{ __('Slider') }}</label>
                                    <div class="image-input image-input-empty image-input-outline" id="logo"
                                        style="background-image: url({{  $sliders->getFirstMediaUrl('sliderImage')  }})">
                                        <div class="image-input-wrapper"></div>
                                        <label
                                            class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow"
                                            data-action="change" data-toggle="tooltip" title=""
                                            data-original-title="Change avatar">
                                            <i class="fa fa-pen icon-sm text-muted"></i>
                                            <input type="file" name="Slider_imgae" accept=".png, .jpg, .jpeg" />
                                            <input type="hidden" name="Slider_imgae" />
                                            <img>
                                        </label>
                                        <span
                                            class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow"
                                            data-action="cancel" data-toggle="tooltip" title="Cancel avatar">
                                            <i class="ki ki-bold-close icon-xs text-muted"></i>
                                        </span>
                                        <span
                                            class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow"
                                            data-action="remove" data-toggle="tooltip" title="Remove avatar">
                                            <i class="ki ki-bold-close icon-xs text-muted"></i>
                                        </span>
                                        @error('Slider_imgae')
                                            <div class="text-danger">{{ $message }}</div>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-3 col-form-label" for="status">Status</label>
                            <div class="col-md-9">
                                {{-- <input type="hidden"  value="0" name="status" /> --}}
                                <span class="switch switch-icon">
                                    <label>
                                        <input type="checkbox" {{ old('status', $sliders->status) ? 'checked' : null }} value="1 "
                                            name="status" />
                                        <span></span>
                                    </label>
                                </span>

                                @error('status')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@push('script')
    <script src="{{ asset('assets/dashboard/js/pages/crud/file-upload/image-input.js') }}"></script>
    <script>
        let avatar5 = new KTImageInput('logo');
        let avatar6 = new KTImageInput('footerLogo');
    </script>
@endpush

resources/views/dashboard/slider/index.blade.php
@extends('layouts.dashboard')
@section('content')
    <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
        <div class="kt-portlet kt-portlet--mobile">
            <div class="card card-custom mt-5">
                <div class="card-header flex-wrap border-0 pt-6 pb-0">
                    <div class="card-title">
                        <h3 class="card-label">Slider List</h3>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-separate table-head-custom table-checkable" id="kt_datatable">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Image</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @php
                                $i = 0;
                            @endphp
                            @foreach ($sliders as $slider)

                                <tr>
                                    <td>{{ $i++ }}</td>
                                    <td>{{ $slider->name }}</td>
                                    <td>
                                        @if ($slider->hasMedia('sliderImage'))
                                            <img src="{{ $slider->getFirstMediaUrl('sliderImage') }}"
                                                width="120px">
                                        @endif
                                    </td>
                                    <td>
                                        @if ($slider->status == 1)
                                            {{ 'Active' }}
                                        @else
                                            {{ 'Deactive' }}
                                        @endif

                                    </td>
                                    </td>
                                    <td nowrap="nowrap">
                                        <a href="{{ route('slider.edit', $slider->id) }}"
                                            class="btn btn-icon btn-light btn-hover-primary btn-sm mx-3">
                                            <span class="svg-icon svg-icon-md svg-icon-primary">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px"
                                                    viewBox="0 0 24 24" version="1.1">
                                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                        <rect x="0" y="0" width="24" height="24"></rect>
                                                        <path
                                                            d="M12.2674799,18.2323597 L12.0084872,5.45852451 C12.0004303,5.06114792 12.1504154,4.6768183 12.4255037,4.38993949 L15.0030167,1.70195304 L17.5910752,4.40093695 C17.8599071,4.6812911 18.0095067,5.05499603 18.0083938,5.44341307 L17.9718262,18.2062508 C17.9694575,19.0329966 17.2985816,19.701953 16.4718324,19.701953 L13.7671717,19.701953 C12.9505952,19.701953 12.2840328,19.0487684 12.2674799,18.2323597 Z"
                                                            fill="#000000" fill-rule="nonzero"
                                                            transform="translate(14.701953, 10.701953) rotate(-135.000000) translate(-14.701953, -10.701953)">
                                                        </path>
                                                        <path
                                                            d="M12.9,2 C13.4522847,2 13.9,2.44771525 13.9,3 C13.9,3.55228475 13.4522847,4 12.9,4 L6,4 C4.8954305,4 4,4.8954305 4,6 L4,18 C4,19.1045695 4.8954305,20 6,20 L18,20 C19.1045695,20 20,19.1045695 20,18 L20,13 C20,12.4477153 20.4477153,12 21,12 C21.5522847,12 22,12.4477153 22,13 L22,18 C22,20.209139 20.209139,22 18,22 L6,22 C3.790861,22 2,20.209139 2,18 L2,6 C2,3.790861 3.790861,2 6,2 L12.9,2 Z"
                                                            fill="#000000" fill-rule="nonzero" opacity="0.3"></path>
                                                    </g>
                                                </svg>
                                            </span>
                                        </a>
                                        <form method="post" action="{{ route('slider.destroy', $slider->id) }}"
                                            class="d-inline-block">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit"
                                                onclick="return confirm('Are you sure you want to delete this item?');"
                                                class="btn btn-icon btn-light btn-hover-danger btn-sm">
                                                <span class="svg-icon svg-icon-md svg-icon-primary">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px"
                                                        viewBox="0 0 24 24" version="1.1">
                                                        <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                            <rect x="0" y="0" width="24" height="24"></rect>
                                                            <path
                                                                d="M6,8 L6,20.5 C6,21.3284271 6.67157288,22 7.5,22 L16.5,22 C17.3284271,22 18,21.3284271 18,20.5 L18,8 L6,8 Z"
                                                                fill="#000000" fill-rule="nonzero"></path>
                                                            <path
                                                                d="M14,4.5 L14,4 C14,3.44771525 13.5522847,3 13,3 L11,3 C10.4477153,3 10,3.44771525 10,4 L10,4.5 L5.5,4.5 C5.22385763,4.5 5,4.72385763 5,5 L5,5.5 C5,5.77614237 5.22385763,6 5.5,6 L18.5,6 C18.7761424,6 19,5.77614237 19,5.5 L19,5 C19,4.72385763 18.7761424,4.5 18.5,4.5 L14,4.5 Z"
                                                                fill="#000000" opacity="0.3"></path>
                                                        </g>
                                                    </svg>
                                                </span>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection